post_live_metrics: Add `_post_in_chunks`.
iterative/dvc-studio-client pull request #80
Opened 2023-08-21 17:06 UTC by daavoo

- Post metrics and parameters separately
- Post plots in chunks smaller than 30MB

Optimistically? expect metrics and parameters to not exceed 30MB.

I have manually tested against Studio Prod sending updates with plots > 120MB.

- [ ] Tests

2023-08-21 18:29 UTC, dberenbaum commented
Any concerns about this spamming studio too much? Thinking of https://iterativeai.slack.com/archives/C01116VLT7D/p1692452930044229.

2023-08-22 08:17 UTC, daavoo commented
> Any concerns about this spamming studio too much? Thinking of https://iterativeai.slack.com/archives/C01116VLT7D/p1692452930044229.

As I understood it, the problem in the link was not about too many requests from the client to the server.
 The problem was (still is) in the backend querying the database in a very inefficient way, so a single request in a project with a lot of steps per linear plot caused / can trigger this (https://github.com/iterative/studio/issues/7256).

Anyhow, the change here mainly affects images, which are handled differently from linear plots (the source of the linked problem).

The main difference is when there the size of the images exceeds the server limit per single request:

Without this P.R, we just fail to send data on each step and try to send it in the next one. Failing forever and the request keeps getting bigger.
With this P.R:, we are able to send the data at each step bypassing the server limit.

2023-08-23 22:51 UTC, shcheklein commented
I think it doesn't have to wait. The only thing that comes to my mind to check (besides the basic review, @amritghimire can you do that please?)- align the limits with Studio `big_files` check. See here for example - https://github.com/iterative/studio/pull/7299/files#diff-a67d283c73e8021405df0b1de3fb8dcf570563c21c70de5324cc2d8b661e561fR36

We skip 10Mb files on Studio (so they will disappear as we then parse an experiment).

Also, I now put a limit of 200 files per directory (not ideal, see the discussion and chime in the PR)- but as a safe guard. Here (or on the Studio side? or both?) we probably also want to limit the number of chunks, or number of files, etc.

2023-08-24 06:55 UTC, amritghimire requested changes

2023-08-24 06:55 UTC, amritghimire commented on src/dvc_studio_client/post_live_metrics.py
> +MAX_CHUNK_SIZE = 29000000
Lets add a comment with human readable size for an easy picture here,

2023-09-01 14:35 UTC, daavoo commented
> I think it doesn't have to wait. The only thing that comes to my mind to check (besides the basic review, @amritghimire can you do that please?)- align the limits with Studio `big_files` check. See here for example - https://github.com/iterative/studio/pull/7299/files#diff-a67d283c73e8021405df0b1de3fb8dcf570563c21c70de5324cc2d8b661e561fR36
> 
> We skip 10Mb files on Studio (so they will disappear as we then parse an experiment).

> Also, I now put a limit of 200 files per directory (not ideal, see the discussion and chime in the PR)- but as a safe guard. Here (or on the Studio side? or both?) we probably also want to limit the number of chunks, or number of files, etc.

Added both checks

2023-09-01 14:40 UTC, merged